version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11.4
    steps:
      - checkout
      - run: go get -v -u github.com/chfanghr/trackDownloader/...
      - run: go install -v -ldflags '-X main.version=0.0.1beta.x' github.com/chfanghr/trackDownloader
      - run: cat '$GOPATH/bin/trackDownloader' <<EOF
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
