version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    steps:
      - checkout
      - run: sudo chmod -R +x ./.circleci/*.sh
      - run: .circleci/build.sh .
      - store_artifacts: 
          path: /build/build.tar
