version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.12
    working_directory: /trackDownloader
    steps:
      - checkout
      - run: sudo chmod -R +x ./.circleci/*.sh
      - run: .circleci/build.sh
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
